--------------------------------------------------------
--  DDL for Index IDX_PK_ID_CONSULTORIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSODB"."IDX_PK_ID_CONSULTORIO" ON "CURSODB"."TBL_CONSULTORIOS" ("ID_CONSULTORIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_IDX" ;
