--------------------------------------------------------
--  DDL for Table TBL_CITAS
--------------------------------------------------------

  CREATE TABLE "CURSODB"."TBL_CITAS" 
   (	"ID_CITA" NUMBER, 
	"COSTO_TOTAL" NUMBER, 
	"FECHA_HORA" DATE, 
	"ID_PACIENTE" NUMBER, 
	"ID_CONSULTORIO" NUMBER, 
	"NRP_ODONTOLOGO" NUMBER, 
	"ID_ESTADO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_DAT" ;

   COMMENT ON COLUMN "CURSODB"."TBL_CITAS"."ID_CITA" IS 'ID DEL CITA';
   COMMENT ON COLUMN "CURSODB"."TBL_CITAS"."COSTO_TOTAL" IS 'cOSTO TOTAL';
   COMMENT ON COLUMN "CURSODB"."TBL_CITAS"."FECHA_HORA" IS 'FECHA DE LA CITA';
   COMMENT ON COLUMN "CURSODB"."TBL_CITAS"."ID_PACIENTE" IS 'ID DEL PACIENTE';
   COMMENT ON COLUMN "CURSODB"."TBL_CITAS"."ID_CONSULTORIO" IS 'ID DEL CONSULTORIO';
   COMMENT ON COLUMN "CURSODB"."TBL_CITAS"."NRP_ODONTOLOGO" IS 'ID DEL ODONTOLOGO';
   COMMENT ON COLUMN "CURSODB"."TBL_CITAS"."ID_ESTADO" IS 'ID DEL ESTADO';
   COMMENT ON TABLE "CURSODB"."TBL_CITAS"  IS 'Tabla de CITAS';
