--------------------------------------------------------
--  DDL for Table TBL_ODONTOLOGOS
--------------------------------------------------------

  CREATE TABLE "CURSODB"."TBL_ODONTOLOGOS" 
   (	"NRP_ODONTOLOGO" NUMBER, 
	"ID_ESPECIALIDAD" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"CORREO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_DAT" ;

   COMMENT ON COLUMN "CURSODB"."TBL_ODONTOLOGOS"."NRP_ODONTOLOGO" IS 'ID DEL ODONTOLOGO';
   COMMENT ON COLUMN "CURSODB"."TBL_ODONTOLOGOS"."ID_ESPECIALIDAD" IS 'ESPECIALIDAD DEL ODONTOLOGO';
   COMMENT ON COLUMN "CURSODB"."TBL_ODONTOLOGOS"."NOMBRE" IS 'NOMBRE DEL ODONTOLOGO';
   COMMENT ON COLUMN "CURSODB"."TBL_ODONTOLOGOS"."CORREO" IS 'CORREO';
   COMMENT ON TABLE "CURSODB"."TBL_ODONTOLOGOS"  IS 'Tabla de ODONTOLOGOS';
