--------------------------------------------------------
--  DDL for Table TBL_CONSULTORIOS
--------------------------------------------------------

  CREATE TABLE "CURSODB"."TBL_CONSULTORIOS" 
   (	"ID_CONSULTORIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_DAT" ;

   COMMENT ON COLUMN "CURSODB"."TBL_CONSULTORIOS"."ID_CONSULTORIO" IS 'ID DE CONSULTORIO';
   COMMENT ON TABLE "CURSODB"."TBL_CONSULTORIOS"  IS 'Tabla de consultorios';
