--------------------------------------------------------
--  DDL for Table TBL_ESPECIALIDADES
--------------------------------------------------------

  CREATE TABLE "CURSODB"."TBL_ESPECIALIDADES" 
   (	"ID_ESPECIALIDAD" NUMBER, 
	"DESCRIPCION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_DAT" ;

   COMMENT ON COLUMN "CURSODB"."TBL_ESPECIALIDADES"."ID_ESPECIALIDAD" IS 'ID ESPECIALIDAD';
   COMMENT ON COLUMN "CURSODB"."TBL_ESPECIALIDADES"."DESCRIPCION" IS 'DESCRIPCION';
   COMMENT ON TABLE "CURSODB"."TBL_ESPECIALIDADES"  IS 'Tabla de especialidades';
