--------------------------------------------------------
--  DDL for Table TBL_TRATAMIENTOS
--------------------------------------------------------

  CREATE TABLE "CURSODB"."TBL_TRATAMIENTOS" 
   (	"ID_TRATAMIENTO" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(100 BYTE), 
	"COSTO_BASE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_DAT" ;

   COMMENT ON COLUMN "CURSODB"."TBL_TRATAMIENTOS"."ID_TRATAMIENTO" IS 'ID DEL TRATAMIENTO';
   COMMENT ON COLUMN "CURSODB"."TBL_TRATAMIENTOS"."NOMBRE" IS 'NOMBRE DEL TRATAMIENTO';
   COMMENT ON COLUMN "CURSODB"."TBL_TRATAMIENTOS"."DESCRIPCION" IS 'DESCRIPCION DEL TRATAMIENTO';
   COMMENT ON COLUMN "CURSODB"."TBL_TRATAMIENTOS"."COSTO_BASE" IS 'COSTO BASE';
   COMMENT ON TABLE "CURSODB"."TBL_TRATAMIENTOS"  IS 'Tabla de tratamientos';
