--------------------------------------------------------
--  DDL for Table TBL_PACIENTES
--------------------------------------------------------

  CREATE TABLE "CURSODB"."TBL_PACIENTES" 
   (	"ID_PACIENTE" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DNI" NUMBER(10,0), 
	"TELEFONO" VARCHAR2(15 BYTE), 
	"CORREO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_DAT" ;

   COMMENT ON COLUMN "CURSODB"."TBL_PACIENTES"."ID_PACIENTE" IS 'ID DEL PACIENTE';
   COMMENT ON COLUMN "CURSODB"."TBL_PACIENTES"."NOMBRE" IS 'NOMBRE DE PACIENTES';
   COMMENT ON COLUMN "CURSODB"."TBL_PACIENTES"."DNI" IS 'DNI';
   COMMENT ON COLUMN "CURSODB"."TBL_PACIENTES"."TELEFONO" IS 'TELEFONO DE PACIENTE';
   COMMENT ON COLUMN "CURSODB"."TBL_PACIENTES"."CORREO" IS 'CORREO';
   COMMENT ON TABLE "CURSODB"."TBL_PACIENTES"  IS 'Tabla de pacientes';
