--------------------------------------------------------
-- Archivo creado  - lunes-junio-15-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ODONTOLOGOS
--------------------------------------------------------

   CREATE SEQUENCE  "CURSODB"."ODONTOLOGOS"  MINVALUE 1000 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1021 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence TBL_CITA
--------------------------------------------------------

   CREATE SEQUENCE  "CURSODB"."TBL_CITA"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence TBL_PACIENTE
--------------------------------------------------------

   CREATE SEQUENCE  "CURSODB"."TBL_PACIENTE"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table TBL_APLICA
--------------------------------------------------------

  CREATE TABLE "CURSODB"."TBL_APLICA" 
   (	"ID_TRATAMIENTO" NUMBER, 
	"ID_CITA" NUMBER, 
	"OBSERVACION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_DAT" ;
--------------------------------------------------------
--  DDL for Table TBL_CITAS
--------------------------------------------------------

  CREATE TABLE "CURSODB"."TBL_CITAS" 
   (	"ID_CITA" NUMBER, 
	"COSTO_TOTAL" NUMBER, 
	"FECHA_HORA" DATE, 
	"ID_PACIENTE" NUMBER, 
	"ID_CONSULTORIO" NUMBER, 
	"NRP_ODONTOLOGO" NUMBER, 
	"ID_ESTADO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_DAT" ;

   COMMENT ON COLUMN "CURSODB"."TBL_CITAS"."ID_CITA" IS 'ID DEL CITA';
   COMMENT ON COLUMN "CURSODB"."TBL_CITAS"."COSTO_TOTAL" IS 'cOSTO TOTAL';
   COMMENT ON COLUMN "CURSODB"."TBL_CITAS"."FECHA_HORA" IS 'FECHA DE LA CITA';
   COMMENT ON COLUMN "CURSODB"."TBL_CITAS"."ID_PACIENTE" IS 'ID DEL PACIENTE';
   COMMENT ON COLUMN "CURSODB"."TBL_CITAS"."ID_CONSULTORIO" IS 'ID DEL CONSULTORIO';
   COMMENT ON COLUMN "CURSODB"."TBL_CITAS"."NRP_ODONTOLOGO" IS 'ID DEL ODONTOLOGO';
   COMMENT ON COLUMN "CURSODB"."TBL_CITAS"."ID_ESTADO" IS 'ID DEL ESTADO';
   COMMENT ON TABLE "CURSODB"."TBL_CITAS"  IS 'Tabla de CITAS';
--------------------------------------------------------
--  DDL for Table TBL_CONSULTORIOS
--------------------------------------------------------

  CREATE TABLE "CURSODB"."TBL_CONSULTORIOS" 
   (	"ID_CONSULTORIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_DAT" ;

   COMMENT ON COLUMN "CURSODB"."TBL_CONSULTORIOS"."ID_CONSULTORIO" IS 'ID DE CONSULTORIO';
   COMMENT ON TABLE "CURSODB"."TBL_CONSULTORIOS"  IS 'Tabla de consultorios';
--------------------------------------------------------
--  DDL for Table TBL_ESPECIALIDADES
--------------------------------------------------------

  CREATE TABLE "CURSODB"."TBL_ESPECIALIDADES" 
   (	"ID_ESPECIALIDAD" NUMBER, 
	"DESCRIPCION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_DAT" ;

   COMMENT ON COLUMN "CURSODB"."TBL_ESPECIALIDADES"."ID_ESPECIALIDAD" IS 'ID ESPECIALIDAD';
   COMMENT ON COLUMN "CURSODB"."TBL_ESPECIALIDADES"."DESCRIPCION" IS 'DESCRIPCION';
   COMMENT ON TABLE "CURSODB"."TBL_ESPECIALIDADES"  IS 'Tabla de especialidades';
--------------------------------------------------------
--  DDL for Table TBL_ESTADOS
--------------------------------------------------------

  CREATE TABLE "CURSODB"."TBL_ESTADOS" 
   (	"ID_ESTADOS" NUMBER, 
	"DESCRIPCION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_DAT" ;

   COMMENT ON COLUMN "CURSODB"."TBL_ESTADOS"."ID_ESTADOS" IS 'ID DE ESTADOS';
   COMMENT ON COLUMN "CURSODB"."TBL_ESTADOS"."DESCRIPCION" IS 'DESCRIPCION';
   COMMENT ON TABLE "CURSODB"."TBL_ESTADOS"  IS 'Tabla de estados';
--------------------------------------------------------
--  DDL for Table TBL_ODONTOLOGOS
--------------------------------------------------------

  CREATE TABLE "CURSODB"."TBL_ODONTOLOGOS" 
   (	"NRP_ODONTOLOGO" NUMBER, 
	"ID_ESPECIALIDAD" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"CORREO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_DAT" ;

   COMMENT ON COLUMN "CURSODB"."TBL_ODONTOLOGOS"."NRP_ODONTOLOGO" IS 'ID DEL ODONTOLOGO';
   COMMENT ON COLUMN "CURSODB"."TBL_ODONTOLOGOS"."ID_ESPECIALIDAD" IS 'ESPECIALIDAD DEL ODONTOLOGO';
   COMMENT ON COLUMN "CURSODB"."TBL_ODONTOLOGOS"."NOMBRE" IS 'NOMBRE DEL ODONTOLOGO';
   COMMENT ON COLUMN "CURSODB"."TBL_ODONTOLOGOS"."CORREO" IS 'CORREO';
   COMMENT ON TABLE "CURSODB"."TBL_ODONTOLOGOS"  IS 'Tabla de ODONTOLOGOS';
--------------------------------------------------------
--  DDL for Table TBL_PACIENTES
--------------------------------------------------------

  CREATE TABLE "CURSODB"."TBL_PACIENTES" 
   (	"ID_PACIENTE" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DNI" NUMBER(10,0), 
	"TELEFONO" VARCHAR2(15 BYTE), 
	"CORREO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_DAT" ;

   COMMENT ON COLUMN "CURSODB"."TBL_PACIENTES"."ID_PACIENTE" IS 'ID DEL PACIENTE';
   COMMENT ON COLUMN "CURSODB"."TBL_PACIENTES"."NOMBRE" IS 'NOMBRE DE PACIENTES';
   COMMENT ON COLUMN "CURSODB"."TBL_PACIENTES"."DNI" IS 'DNI';
   COMMENT ON COLUMN "CURSODB"."TBL_PACIENTES"."TELEFONO" IS 'TELEFONO DE PACIENTE';
   COMMENT ON COLUMN "CURSODB"."TBL_PACIENTES"."CORREO" IS 'CORREO';
   COMMENT ON TABLE "CURSODB"."TBL_PACIENTES"  IS 'Tabla de pacientes';
--------------------------------------------------------
--  DDL for Table TBL_TRATAMIENTOS
--------------------------------------------------------

  CREATE TABLE "CURSODB"."TBL_TRATAMIENTOS" 
   (	"ID_TRATAMIENTO" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(100 BYTE), 
	"COSTO_BASE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_DAT" ;

   COMMENT ON COLUMN "CURSODB"."TBL_TRATAMIENTOS"."ID_TRATAMIENTO" IS 'ID DEL TRATAMIENTO';
   COMMENT ON COLUMN "CURSODB"."TBL_TRATAMIENTOS"."NOMBRE" IS 'NOMBRE DEL TRATAMIENTO';
   COMMENT ON COLUMN "CURSODB"."TBL_TRATAMIENTOS"."DESCRIPCION" IS 'DESCRIPCION DEL TRATAMIENTO';
   COMMENT ON COLUMN "CURSODB"."TBL_TRATAMIENTOS"."COSTO_BASE" IS 'COSTO BASE';
   COMMENT ON TABLE "CURSODB"."TBL_TRATAMIENTOS"  IS 'Tabla de tratamientos';
REM INSERTING into CURSODB.TBL_APLICA
SET DEFINE OFF;
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('1','1','Tratamiento principal');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('2','1','Tratamiento complementario');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('2','2','Tratamiento principal');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('3','2','Tratamiento complementario');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('3','3','Tratamiento principal');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('4','3','Tratamiento complementario');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('4','4','Tratamiento principal');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('5','4','Tratamiento complementario');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('5','5','Tratamiento principal');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('6','5','Tratamiento complementario');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('6','6','Tratamiento principal');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('7','6','Tratamiento complementario');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('7','7','Tratamiento principal');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('8','7','Tratamiento complementario');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('8','8','Tratamiento principal');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('9','8','Tratamiento complementario');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('9','9','Tratamiento principal');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('10','9','Tratamiento complementario');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('10','10','Tratamiento principal');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('11','10','Tratamiento complementario');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('11','11','Tratamiento principal');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('1','11','Tratamiento complementario');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('1','12','Tratamiento principal');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('2','12','Tratamiento complementario');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('2','13','Tratamiento principal');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('3','13','Tratamiento complementario');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('3','14','Tratamiento principal');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('4','14','Tratamiento complementario');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('4','15','Tratamiento principal');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('5','15','Tratamiento complementario');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('5','16','Tratamiento principal');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('6','16','Tratamiento complementario');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('6','17','Tratamiento principal');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('7','17','Tratamiento complementario');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('7','18','Tratamiento principal');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('8','18','Tratamiento complementario');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('8','19','Tratamiento principal');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('9','19','Tratamiento complementario');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('9','20','Tratamiento principal');
Insert into CURSODB.TBL_APLICA (ID_TRATAMIENTO,ID_CITA,OBSERVACION) values ('10','20','Tratamiento complementario');
REM INSERTING into CURSODB.TBL_CITAS
SET DEFINE OFF;
Insert into CURSODB.TBL_CITAS (ID_CITA,COSTO_TOTAL,FECHA_HORA,ID_PACIENTE,ID_CONSULTORIO,NRP_ODONTOLOGO,ID_ESTADO) values ('1','60000',to_date('01/01/26','DD/MM/RR'),'1','1','1001','2');
Insert into CURSODB.TBL_CITAS (ID_CITA,COSTO_TOTAL,FECHA_HORA,ID_PACIENTE,ID_CONSULTORIO,NRP_ODONTOLOGO,ID_ESTADO) values ('2','70000',to_date('02/02/26','DD/MM/RR'),'2','2','1002','3');
Insert into CURSODB.TBL_CITAS (ID_CITA,COSTO_TOTAL,FECHA_HORA,ID_PACIENTE,ID_CONSULTORIO,NRP_ODONTOLOGO,ID_ESTADO) values ('3','80000',to_date('03/03/26','DD/MM/RR'),'3','3','1003','4');
Insert into CURSODB.TBL_CITAS (ID_CITA,COSTO_TOTAL,FECHA_HORA,ID_PACIENTE,ID_CONSULTORIO,NRP_ODONTOLOGO,ID_ESTADO) values ('4','90000',to_date('04/04/26','DD/MM/RR'),'4','4','1004','5');
Insert into CURSODB.TBL_CITAS (ID_CITA,COSTO_TOTAL,FECHA_HORA,ID_PACIENTE,ID_CONSULTORIO,NRP_ODONTOLOGO,ID_ESTADO) values ('5','100000',to_date('05/05/26','DD/MM/RR'),'5','5','1005','1');
Insert into CURSODB.TBL_CITAS (ID_CITA,COSTO_TOTAL,FECHA_HORA,ID_PACIENTE,ID_CONSULTORIO,NRP_ODONTOLOGO,ID_ESTADO) values ('6','110000',to_date('06/06/26','DD/MM/RR'),'6','6','1006','2');
Insert into CURSODB.TBL_CITAS (ID_CITA,COSTO_TOTAL,FECHA_HORA,ID_PACIENTE,ID_CONSULTORIO,NRP_ODONTOLOGO,ID_ESTADO) values ('7','120000',to_date('07/01/26','DD/MM/RR'),'7','7','1007','3');
Insert into CURSODB.TBL_CITAS (ID_CITA,COSTO_TOTAL,FECHA_HORA,ID_PACIENTE,ID_CONSULTORIO,NRP_ODONTOLOGO,ID_ESTADO) values ('8','130000',to_date('08/02/26','DD/MM/RR'),'8','8','1008','4');
Insert into CURSODB.TBL_CITAS (ID_CITA,COSTO_TOTAL,FECHA_HORA,ID_PACIENTE,ID_CONSULTORIO,NRP_ODONTOLOGO,ID_ESTADO) values ('9','140000',to_date('09/03/26','DD/MM/RR'),'9','9','1009','5');
Insert into CURSODB.TBL_CITAS (ID_CITA,COSTO_TOTAL,FECHA_HORA,ID_PACIENTE,ID_CONSULTORIO,NRP_ODONTOLOGO,ID_ESTADO) values ('10','150000',to_date('10/04/26','DD/MM/RR'),'10','10','1010','1');
Insert into CURSODB.TBL_CITAS (ID_CITA,COSTO_TOTAL,FECHA_HORA,ID_PACIENTE,ID_CONSULTORIO,NRP_ODONTOLOGO,ID_ESTADO) values ('11','160000',to_date('11/05/26','DD/MM/RR'),'11','11','1011','2');
Insert into CURSODB.TBL_CITAS (ID_CITA,COSTO_TOTAL,FECHA_HORA,ID_PACIENTE,ID_CONSULTORIO,NRP_ODONTOLOGO,ID_ESTADO) values ('12','170000',to_date('12/06/26','DD/MM/RR'),'12','1','1012','3');
Insert into CURSODB.TBL_CITAS (ID_CITA,COSTO_TOTAL,FECHA_HORA,ID_PACIENTE,ID_CONSULTORIO,NRP_ODONTOLOGO,ID_ESTADO) values ('13','180000',to_date('13/01/26','DD/MM/RR'),'13','2','1013','4');
Insert into CURSODB.TBL_CITAS (ID_CITA,COSTO_TOTAL,FECHA_HORA,ID_PACIENTE,ID_CONSULTORIO,NRP_ODONTOLOGO,ID_ESTADO) values ('14','190000',to_date('14/02/26','DD/MM/RR'),'14','3','1014','5');
Insert into CURSODB.TBL_CITAS (ID_CITA,COSTO_TOTAL,FECHA_HORA,ID_PACIENTE,ID_CONSULTORIO,NRP_ODONTOLOGO,ID_ESTADO) values ('15','200000',to_date('15/03/26','DD/MM/RR'),'15','4','1015','1');
Insert into CURSODB.TBL_CITAS (ID_CITA,COSTO_TOTAL,FECHA_HORA,ID_PACIENTE,ID_CONSULTORIO,NRP_ODONTOLOGO,ID_ESTADO) values ('16','210000',to_date('16/04/26','DD/MM/RR'),'16','5','1001','2');
Insert into CURSODB.TBL_CITAS (ID_CITA,COSTO_TOTAL,FECHA_HORA,ID_PACIENTE,ID_CONSULTORIO,NRP_ODONTOLOGO,ID_ESTADO) values ('17','220000',to_date('17/05/26','DD/MM/RR'),'17','6','1002','3');
Insert into CURSODB.TBL_CITAS (ID_CITA,COSTO_TOTAL,FECHA_HORA,ID_PACIENTE,ID_CONSULTORIO,NRP_ODONTOLOGO,ID_ESTADO) values ('18','230000',to_date('18/06/26','DD/MM/RR'),'18','7','1003','4');
Insert into CURSODB.TBL_CITAS (ID_CITA,COSTO_TOTAL,FECHA_HORA,ID_PACIENTE,ID_CONSULTORIO,NRP_ODONTOLOGO,ID_ESTADO) values ('19','240000',to_date('19/01/26','DD/MM/RR'),'19','8','1004','5');
Insert into CURSODB.TBL_CITAS (ID_CITA,COSTO_TOTAL,FECHA_HORA,ID_PACIENTE,ID_CONSULTORIO,NRP_ODONTOLOGO,ID_ESTADO) values ('20','250000',to_date('20/02/26','DD/MM/RR'),'20','9','1005','1');
REM INSERTING into CURSODB.TBL_CONSULTORIOS
SET DEFINE OFF;
Insert into CURSODB.TBL_CONSULTORIOS (ID_CONSULTORIO) values ('1');
Insert into CURSODB.TBL_CONSULTORIOS (ID_CONSULTORIO) values ('2');
Insert into CURSODB.TBL_CONSULTORIOS (ID_CONSULTORIO) values ('3');
Insert into CURSODB.TBL_CONSULTORIOS (ID_CONSULTORIO) values ('4');
Insert into CURSODB.TBL_CONSULTORIOS (ID_CONSULTORIO) values ('5');
Insert into CURSODB.TBL_CONSULTORIOS (ID_CONSULTORIO) values ('6');
Insert into CURSODB.TBL_CONSULTORIOS (ID_CONSULTORIO) values ('7');
Insert into CURSODB.TBL_CONSULTORIOS (ID_CONSULTORIO) values ('8');
Insert into CURSODB.TBL_CONSULTORIOS (ID_CONSULTORIO) values ('9');
Insert into CURSODB.TBL_CONSULTORIOS (ID_CONSULTORIO) values ('10');
Insert into CURSODB.TBL_CONSULTORIOS (ID_CONSULTORIO) values ('11');
REM INSERTING into CURSODB.TBL_ESPECIALIDADES
SET DEFINE OFF;
Insert into CURSODB.TBL_ESPECIALIDADES (ID_ESPECIALIDAD,DESCRIPCION) values ('1','Ortodoncia');
Insert into CURSODB.TBL_ESPECIALIDADES (ID_ESPECIALIDAD,DESCRIPCION) values ('2','Endodoncia');
Insert into CURSODB.TBL_ESPECIALIDADES (ID_ESPECIALIDAD,DESCRIPCION) values ('3','Cirugia Oral');
Insert into CURSODB.TBL_ESPECIALIDADES (ID_ESPECIALIDAD,DESCRIPCION) values ('4','Odontopediatria');
Insert into CURSODB.TBL_ESPECIALIDADES (ID_ESPECIALIDAD,DESCRIPCION) values ('5','Implantologia');
Insert into CURSODB.TBL_ESPECIALIDADES (ID_ESPECIALIDAD,DESCRIPCION) values ('6','Estetica');
Insert into CURSODB.TBL_ESPECIALIDADES (ID_ESPECIALIDAD,DESCRIPCION) values ('7','General');
Insert into CURSODB.TBL_ESPECIALIDADES (ID_ESPECIALIDAD,DESCRIPCION) values ('8','Prostodoncia');
Insert into CURSODB.TBL_ESPECIALIDADES (ID_ESPECIALIDAD,DESCRIPCION) values ('9','Maxilofacial');
Insert into CURSODB.TBL_ESPECIALIDADES (ID_ESPECIALIDAD,DESCRIPCION) values ('10','Oclusion');
Insert into CURSODB.TBL_ESPECIALIDADES (ID_ESPECIALIDAD,DESCRIPCION) values ('11','Gerodontologia');
REM INSERTING into CURSODB.TBL_ESTADOS
SET DEFINE OFF;
Insert into CURSODB.TBL_ESTADOS (ID_ESTADOS,DESCRIPCION) values ('1','Confirmada');
Insert into CURSODB.TBL_ESTADOS (ID_ESTADOS,DESCRIPCION) values ('2','Terminada');
Insert into CURSODB.TBL_ESTADOS (ID_ESTADOS,DESCRIPCION) values ('3','En Espera');
Insert into CURSODB.TBL_ESTADOS (ID_ESTADOS,DESCRIPCION) values ('5','No asistio');
Insert into CURSODB.TBL_ESTADOS (ID_ESTADOS,DESCRIPCION) values ('4','Falta de pago');
REM INSERTING into CURSODB.TBL_ODONTOLOGOS
SET DEFINE OFF;
Insert into CURSODB.TBL_ODONTOLOGOS (NRP_ODONTOLOGO,ID_ESPECIALIDAD,NOMBRE,CORREO) values ('1001','1','Juan Perez','jperez@clinica.com');
Insert into CURSODB.TBL_ODONTOLOGOS (NRP_ODONTOLOGO,ID_ESPECIALIDAD,NOMBRE,CORREO) values ('1002','1','Maria Gomez','mgomez@clinica.com');
Insert into CURSODB.TBL_ODONTOLOGOS (NRP_ODONTOLOGO,ID_ESPECIALIDAD,NOMBRE,CORREO) values ('1003','2','Carlos Ruiz','cruiz@clinica.com');
Insert into CURSODB.TBL_ODONTOLOGOS (NRP_ODONTOLOGO,ID_ESPECIALIDAD,NOMBRE,CORREO) values ('1004','2','Ana Torres','atorres@clinica.com');
Insert into CURSODB.TBL_ODONTOLOGOS (NRP_ODONTOLOGO,ID_ESPECIALIDAD,NOMBRE,CORREO) values ('1005','3','Luis Rojas','lrojas@clinica.com');
Insert into CURSODB.TBL_ODONTOLOGOS (NRP_ODONTOLOGO,ID_ESPECIALIDAD,NOMBRE,CORREO) values ('1006','3','Paula Castro','pcastro@clinica.com');
Insert into CURSODB.TBL_ODONTOLOGOS (NRP_ODONTOLOGO,ID_ESPECIALIDAD,NOMBRE,CORREO) values ('1007','4','Andres Diaz','adiaz@clinica.com');
Insert into CURSODB.TBL_ODONTOLOGOS (NRP_ODONTOLOGO,ID_ESPECIALIDAD,NOMBRE,CORREO) values ('1008','5','Sofia Vargas','svargas@clinica.com');
Insert into CURSODB.TBL_ODONTOLOGOS (NRP_ODONTOLOGO,ID_ESPECIALIDAD,NOMBRE,CORREO) values ('1009','6','Jorge Martinez','jmartinez@clinica.com');
Insert into CURSODB.TBL_ODONTOLOGOS (NRP_ODONTOLOGO,ID_ESPECIALIDAD,NOMBRE,CORREO) values ('1010','7','Natalia Herrera','nherrera@clinica.com');
Insert into CURSODB.TBL_ODONTOLOGOS (NRP_ODONTOLOGO,ID_ESPECIALIDAD,NOMBRE,CORREO) values ('1011','1','Ricardo Mendoza','rmendoza@clinica.com');
Insert into CURSODB.TBL_ODONTOLOGOS (NRP_ODONTOLOGO,ID_ESPECIALIDAD,NOMBRE,CORREO) values ('1012','4','Valentina Salazar','vsalazar@clinica.com');
Insert into CURSODB.TBL_ODONTOLOGOS (NRP_ODONTOLOGO,ID_ESPECIALIDAD,NOMBRE,CORREO) values ('1013','7','Camilo Gutierrez','cgutierrez@clinica.com');
Insert into CURSODB.TBL_ODONTOLOGOS (NRP_ODONTOLOGO,ID_ESPECIALIDAD,NOMBRE,CORREO) values ('1014','9','Daniela Moreno','dmoreno@clinica.com');
Insert into CURSODB.TBL_ODONTOLOGOS (NRP_ODONTOLOGO,ID_ESPECIALIDAD,NOMBRE,CORREO) values ('1015','11','Felipe Cardona','fcardona@clinica.com');
REM INSERTING into CURSODB.TBL_PACIENTES
SET DEFINE OFF;
Insert into CURSODB.TBL_PACIENTES (ID_PACIENTE,NOMBRE,DNI,TELEFONO,CORREO) values ('1','Juan David Perez','100000001','3001234001','juan.perez@correo.com');
Insert into CURSODB.TBL_PACIENTES (ID_PACIENTE,NOMBRE,DNI,TELEFONO,CORREO) values ('2','Maria Fernanda Gomez','100000002','3001234002','maria.gomez@correo.com');
Insert into CURSODB.TBL_PACIENTES (ID_PACIENTE,NOMBRE,DNI,TELEFONO,CORREO) values ('3','Carlos Andres Ruiz','100000003','3001234003','carlos.ruiz@correo.com');
Insert into CURSODB.TBL_PACIENTES (ID_PACIENTE,NOMBRE,DNI,TELEFONO,CORREO) values ('4','Ana Sofia Torres','100000004','3001234004','ana.torres@correo.com');
Insert into CURSODB.TBL_PACIENTES (ID_PACIENTE,NOMBRE,DNI,TELEFONO,CORREO) values ('5','Luis Fernando Rojas','100000005','3001234005','luis.rojas@correo.com');
Insert into CURSODB.TBL_PACIENTES (ID_PACIENTE,NOMBRE,DNI,TELEFONO,CORREO) values ('6','Paula Andrea Castro','100000006','3001234006','paula.castro@correo.com');
Insert into CURSODB.TBL_PACIENTES (ID_PACIENTE,NOMBRE,DNI,TELEFONO,CORREO) values ('7','Andres Felipe Diaz','100000007','3001234007','andres.diaz@correo.com');
Insert into CURSODB.TBL_PACIENTES (ID_PACIENTE,NOMBRE,DNI,TELEFONO,CORREO) values ('8','Sofia Valentina Vargas','100000008','3001234008','sofia.vargas@correo.com');
Insert into CURSODB.TBL_PACIENTES (ID_PACIENTE,NOMBRE,DNI,TELEFONO,CORREO) values ('9','Jorge Enrique Martinez','100000009','3001234009','jorge.martinez@correo.com');
Insert into CURSODB.TBL_PACIENTES (ID_PACIENTE,NOMBRE,DNI,TELEFONO,CORREO) values ('10','Natalia Herrera','100000010','3001234010','natalia.herrera@correo.com');
Insert into CURSODB.TBL_PACIENTES (ID_PACIENTE,NOMBRE,DNI,TELEFONO,CORREO) values ('11','Ricardo Mendoza','100000011','3001234011','ricardo.mendoza@correo.com');
Insert into CURSODB.TBL_PACIENTES (ID_PACIENTE,NOMBRE,DNI,TELEFONO,CORREO) values ('12','Valentina Salazar','100000012','3001234012','valentina.salazar@correo.com');
Insert into CURSODB.TBL_PACIENTES (ID_PACIENTE,NOMBRE,DNI,TELEFONO,CORREO) values ('13','Camilo Gutierrez','100000013','3001234013','camilo.gutierrez@correo.com');
Insert into CURSODB.TBL_PACIENTES (ID_PACIENTE,NOMBRE,DNI,TELEFONO,CORREO) values ('14','Daniela Moreno','100000014','3001234014','daniela.moreno@correo.com');
Insert into CURSODB.TBL_PACIENTES (ID_PACIENTE,NOMBRE,DNI,TELEFONO,CORREO) values ('15','Felipe Cardona','100000015','3001234015','felipe.cardona@correo.com');
Insert into CURSODB.TBL_PACIENTES (ID_PACIENTE,NOMBRE,DNI,TELEFONO,CORREO) values ('16','Laura Cristina Ramirez','100000016','3001234016','laura.ramirez@correo.com');
Insert into CURSODB.TBL_PACIENTES (ID_PACIENTE,NOMBRE,DNI,TELEFONO,CORREO) values ('17','Miguel Angel Rodriguez','100000017','3001234017','miguel.rodriguez@correo.com');
Insert into CURSODB.TBL_PACIENTES (ID_PACIENTE,NOMBRE,DNI,TELEFONO,CORREO) values ('18','Tatiana Jimenez','100000018','3001234018','tatiana.jimenez@correo.com');
Insert into CURSODB.TBL_PACIENTES (ID_PACIENTE,NOMBRE,DNI,TELEFONO,CORREO) values ('19','Sebastian Lopez','100000019','3001234019','sebastian.lopez@correo.com');
Insert into CURSODB.TBL_PACIENTES (ID_PACIENTE,NOMBRE,DNI,TELEFONO,CORREO) values ('20','Gabriela Restrepo','100000020','3001234020','gabriela.restrepo@correo.com');
REM INSERTING into CURSODB.TBL_TRATAMIENTOS
SET DEFINE OFF;
Insert into CURSODB.TBL_TRATAMIENTOS (ID_TRATAMIENTO,NOMBRE,DESCRIPCION,COSTO_BASE) values ('1','Limpieza Dental','Eliminación de placa y sarro dental','80000');
Insert into CURSODB.TBL_TRATAMIENTOS (ID_TRATAMIENTO,NOMBRE,DESCRIPCION,COSTO_BASE) values ('2','Blanqueamiento Dental','Mejoramiento estético del color dental','250000');
Insert into CURSODB.TBL_TRATAMIENTOS (ID_TRATAMIENTO,NOMBRE,DESCRIPCION,COSTO_BASE) values ('3','Ortodoncia','Corrección de la posición dental','500000');
Insert into CURSODB.TBL_TRATAMIENTOS (ID_TRATAMIENTO,NOMBRE,DESCRIPCION,COSTO_BASE) values ('4','Endodoncia','Tratamiento de conductos radiculares','300000');
Insert into CURSODB.TBL_TRATAMIENTOS (ID_TRATAMIENTO,NOMBRE,DESCRIPCION,COSTO_BASE) values ('5','Extracción Simple','Remoción de una pieza dental sin cirugía','120000');
Insert into CURSODB.TBL_TRATAMIENTOS (ID_TRATAMIENTO,NOMBRE,DESCRIPCION,COSTO_BASE) values ('6','Extracción Quirúrgica','Remoción compleja de una pieza dental','250000');
Insert into CURSODB.TBL_TRATAMIENTOS (ID_TRATAMIENTO,NOMBRE,DESCRIPCION,COSTO_BASE) values ('7','Sellantes Dentales','Protección preventiva contra caries','90000');
Insert into CURSODB.TBL_TRATAMIENTOS (ID_TRATAMIENTO,NOMBRE,DESCRIPCION,COSTO_BASE) values ('8','Resina Dental','Restauración estética de dientes','150000');
Insert into CURSODB.TBL_TRATAMIENTOS (ID_TRATAMIENTO,NOMBRE,DESCRIPCION,COSTO_BASE) values ('9','Implante Dental','Reemplazo de una pieza dental perdida','1500000');
Insert into CURSODB.TBL_TRATAMIENTOS (ID_TRATAMIENTO,NOMBRE,DESCRIPCION,COSTO_BASE) values ('10','Control Odontológico','Evaluación y seguimiento del paciente','40000');
Insert into CURSODB.TBL_TRATAMIENTOS (ID_TRATAMIENTO,NOMBRE,DESCRIPCION,COSTO_BASE) values ('11','Gerodoncia general','Evaluación y seguimiento del paciente','70000');
--------------------------------------------------------
--  DDL for Index IDX_PK_ID_CITA
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSODB"."IDX_PK_ID_CITA" ON "CURSODB"."TBL_CITAS" ("ID_CITA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_IDX" ;
--------------------------------------------------------
--  DDL for Index IDX_PK_ID_CONSULTORIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSODB"."IDX_PK_ID_CONSULTORIO" ON "CURSODB"."TBL_CONSULTORIOS" ("ID_CONSULTORIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_IDX" ;
--------------------------------------------------------
--  DDL for Index IDX_PK_ID_ESPECIALIDAD
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSODB"."IDX_PK_ID_ESPECIALIDAD" ON "CURSODB"."TBL_ESPECIALIDADES" ("ID_ESPECIALIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_IDX" ;
--------------------------------------------------------
--  DDL for Index IDX_PK_ID_ESTADOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSODB"."IDX_PK_ID_ESTADOS" ON "CURSODB"."TBL_ESTADOS" ("ID_ESTADOS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_IDX" ;
--------------------------------------------------------
--  DDL for Index IDX_PK_ID_PACIENTES
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSODB"."IDX_PK_ID_PACIENTES" ON "CURSODB"."TBL_PACIENTES" ("ID_PACIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_IDX" ;
--------------------------------------------------------
--  DDL for Index IDX_PK_ID_TRATAMIENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSODB"."IDX_PK_ID_TRATAMIENTO" ON "CURSODB"."TBL_TRATAMIENTOS" ("ID_TRATAMIENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_IDX" ;
--------------------------------------------------------
--  DDL for Index IDX_PK_IDTRAT_IDCITA_DETENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSODB"."IDX_PK_IDTRAT_IDCITA_DETENT" ON "CURSODB"."TBL_APLICA" ("ID_TRATAMIENTO", "ID_CITA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_IDX" ;
--------------------------------------------------------
--  DDL for Index IDX_PK_NRP_ODONTOLOGO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSODB"."IDX_PK_NRP_ODONTOLOGO" ON "CURSODB"."TBL_ODONTOLOGOS" ("NRP_ODONTOLOGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_IDX" ;
--------------------------------------------------------
--  DDL for Index IDX_PK_IDTRAT_IDCITA_DETENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSODB"."IDX_PK_IDTRAT_IDCITA_DETENT" ON "CURSODB"."TBL_APLICA" ("ID_TRATAMIENTO", "ID_CITA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_IDX" ;
--------------------------------------------------------
--  DDL for Index IDX_PK_ID_CITA
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSODB"."IDX_PK_ID_CITA" ON "CURSODB"."TBL_CITAS" ("ID_CITA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_IDX" ;
--------------------------------------------------------
--  DDL for Index IDX_PK_ID_CONSULTORIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSODB"."IDX_PK_ID_CONSULTORIO" ON "CURSODB"."TBL_CONSULTORIOS" ("ID_CONSULTORIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_IDX" ;
--------------------------------------------------------
--  DDL for Index IDX_PK_ID_ESPECIALIDAD
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSODB"."IDX_PK_ID_ESPECIALIDAD" ON "CURSODB"."TBL_ESPECIALIDADES" ("ID_ESPECIALIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_IDX" ;
--------------------------------------------------------
--  DDL for Index IDX_PK_ID_ESTADOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSODB"."IDX_PK_ID_ESTADOS" ON "CURSODB"."TBL_ESTADOS" ("ID_ESTADOS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_IDX" ;
--------------------------------------------------------
--  DDL for Index IDX_PK_NRP_ODONTOLOGO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSODB"."IDX_PK_NRP_ODONTOLOGO" ON "CURSODB"."TBL_ODONTOLOGOS" ("NRP_ODONTOLOGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_IDX" ;
--------------------------------------------------------
--  DDL for Index IDX_PK_ID_PACIENTES
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSODB"."IDX_PK_ID_PACIENTES" ON "CURSODB"."TBL_PACIENTES" ("ID_PACIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_IDX" ;
--------------------------------------------------------
--  DDL for Index IDX_PK_ID_TRATAMIENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSODB"."IDX_PK_ID_TRATAMIENTO" ON "CURSODB"."TBL_TRATAMIENTOS" ("ID_TRATAMIENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CURSODB_IDX" ;
--------------------------------------------------------
--  Constraints for Table TBL_APLICA
--------------------------------------------------------

  ALTER TABLE "CURSODB"."TBL_APLICA" ADD CONSTRAINT "PK_IDTRAT_IDCITA_DETENT" PRIMARY KEY ("ID_TRATAMIENTO", "ID_CITA")
  USING INDEX "CURSODB"."IDX_PK_IDTRAT_IDCITA_DETENT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_CITAS
--------------------------------------------------------

  ALTER TABLE "CURSODB"."TBL_CITAS" MODIFY ("ID_CITA" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_CITAS" MODIFY ("COSTO_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_CITAS" MODIFY ("FECHA_HORA" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_CITAS" ADD CONSTRAINT "PK_ID_CITA" PRIMARY KEY ("ID_CITA")
  USING INDEX "CURSODB"."IDX_PK_ID_CITA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_CONSULTORIOS
--------------------------------------------------------

  ALTER TABLE "CURSODB"."TBL_CONSULTORIOS" MODIFY ("ID_CONSULTORIO" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_CONSULTORIOS" ADD CONSTRAINT "PK_ID_CONSULTORIO" PRIMARY KEY ("ID_CONSULTORIO")
  USING INDEX "CURSODB"."IDX_PK_ID_CONSULTORIO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_ESPECIALIDADES
--------------------------------------------------------

  ALTER TABLE "CURSODB"."TBL_ESPECIALIDADES" MODIFY ("ID_ESPECIALIDAD" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_ESPECIALIDADES" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_ESPECIALIDADES" ADD CONSTRAINT "PK_ID_ESPECIALIDAD" PRIMARY KEY ("ID_ESPECIALIDAD")
  USING INDEX "CURSODB"."IDX_PK_ID_ESPECIALIDAD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_ESTADOS
--------------------------------------------------------

  ALTER TABLE "CURSODB"."TBL_ESTADOS" MODIFY ("ID_ESTADOS" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_ESTADOS" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_ESTADOS" ADD CONSTRAINT "PK_ID_ESTADOS" PRIMARY KEY ("ID_ESTADOS")
  USING INDEX "CURSODB"."IDX_PK_ID_ESTADOS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_ODONTOLOGOS
--------------------------------------------------------

  ALTER TABLE "CURSODB"."TBL_ODONTOLOGOS" MODIFY ("NRP_ODONTOLOGO" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_ODONTOLOGOS" MODIFY ("ID_ESPECIALIDAD" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_ODONTOLOGOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_ODONTOLOGOS" MODIFY ("CORREO" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_ODONTOLOGOS" ADD CONSTRAINT "PK_NRP_ODONTOLOGO" PRIMARY KEY ("NRP_ODONTOLOGO")
  USING INDEX "CURSODB"."IDX_PK_NRP_ODONTOLOGO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_PACIENTES
--------------------------------------------------------

  ALTER TABLE "CURSODB"."TBL_PACIENTES" MODIFY ("ID_PACIENTE" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_PACIENTES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_PACIENTES" MODIFY ("DNI" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_PACIENTES" ADD CONSTRAINT "PK_ID_PACIENTES" PRIMARY KEY ("ID_PACIENTE")
  USING INDEX "CURSODB"."IDX_PK_ID_PACIENTES"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_TRATAMIENTOS
--------------------------------------------------------

  ALTER TABLE "CURSODB"."TBL_TRATAMIENTOS" MODIFY ("ID_TRATAMIENTO" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_TRATAMIENTOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_TRATAMIENTOS" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_TRATAMIENTOS" MODIFY ("COSTO_BASE" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_TRATAMIENTOS" ADD CONSTRAINT "PK_ID_TRATAMIENTO" PRIMARY KEY ("ID_TRATAMIENTO")
  USING INDEX "CURSODB"."IDX_PK_ID_TRATAMIENTO"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_APLICA
--------------------------------------------------------

  ALTER TABLE "CURSODB"."TBL_APLICA" ADD CONSTRAINT "FK_ID_TRATAMIENTO" FOREIGN KEY ("ID_TRATAMIENTO")
	  REFERENCES "CURSODB"."TBL_TRATAMIENTOS" ("ID_TRATAMIENTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_CITAS
--------------------------------------------------------

  ALTER TABLE "CURSODB"."TBL_CITAS" ADD CONSTRAINT "FK_ID_PACIENTE" FOREIGN KEY ("ID_PACIENTE")
	  REFERENCES "CURSODB"."TBL_PACIENTES" ("ID_PACIENTE") ENABLE;
  ALTER TABLE "CURSODB"."TBL_CITAS" ADD CONSTRAINT "FK_ID_CONSULTORIO" FOREIGN KEY ("ID_CONSULTORIO")
	  REFERENCES "CURSODB"."TBL_CONSULTORIOS" ("ID_CONSULTORIO") ENABLE;
  ALTER TABLE "CURSODB"."TBL_CITAS" ADD CONSTRAINT "FK_NRP_ODONTOLOGO" FOREIGN KEY ("NRP_ODONTOLOGO")
	  REFERENCES "CURSODB"."TBL_ODONTOLOGOS" ("NRP_ODONTOLOGO") ENABLE;
  ALTER TABLE "CURSODB"."TBL_CITAS" ADD CONSTRAINT "FK_ID_ESTADO" FOREIGN KEY ("ID_ESTADO")
	  REFERENCES "CURSODB"."TBL_ESTADOS" ("ID_ESTADOS") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_ODONTOLOGOS
--------------------------------------------------------

  ALTER TABLE "CURSODB"."TBL_ODONTOLOGOS" ADD CONSTRAINT "FK_ID_ESPECIALIDAD" FOREIGN KEY ("ID_ESPECIALIDAD")
	  REFERENCES "CURSODB"."TBL_ESPECIALIDADES" ("ID_ESPECIALIDAD") ENABLE;
