REM INSERTING into CURSODB.TBL_ESPECIALIDADES
SET DEFINE OFF;
Insert into CURSODB.TBL_ESPECIALIDADES (ID_ESPECIALIDAD,DESCRIPCION) values ('1','Ortodoncia');
Insert into CURSODB.TBL_ESPECIALIDADES (ID_ESPECIALIDAD,DESCRIPCION) values ('2','Endodoncia');
Insert into CURSODB.TBL_ESPECIALIDADES (ID_ESPECIALIDAD,DESCRIPCION) values ('3','Cirugia Oral');
Insert into CURSODB.TBL_ESPECIALIDADES (ID_ESPECIALIDAD,DESCRIPCION) values ('4','Odontopediatria');
Insert into CURSODB.TBL_ESPECIALIDADES (ID_ESPECIALIDAD,DESCRIPCION) values ('5','Implantologia');
Insert into CURSODB.TBL_ESPECIALIDADES (ID_ESPECIALIDAD,DESCRIPCION) values ('6','Estetica');
Insert into CURSODB.TBL_ESPECIALIDADES (ID_ESPECIALIDAD,DESCRIPCION) values ('7','General');
Insert into CURSODB.TBL_ESPECIALIDADES (ID_ESPECIALIDAD,DESCRIPCION) values ('8','Prostodoncia');
Insert into CURSODB.TBL_ESPECIALIDADES (ID_ESPECIALIDAD,DESCRIPCION) values ('9','Maxilofacial');
Insert into CURSODB.TBL_ESPECIALIDADES (ID_ESPECIALIDAD,DESCRIPCION) values ('10','Oclusion');
Insert into CURSODB.TBL_ESPECIALIDADES (ID_ESPECIALIDAD,DESCRIPCION) values ('11','Gerodontologia');
