REM INSERTING into CURSODB.TBL_CONSULTORIOS
SET DEFINE OFF;
Insert into CURSODB.TBL_CONSULTORIOS (ID_CONSULTORIO) values ('1');
Insert into CURSODB.TBL_CONSULTORIOS (ID_CONSULTORIO) values ('2');
Insert into CURSODB.TBL_CONSULTORIOS (ID_CONSULTORIO) values ('3');
Insert into CURSODB.TBL_CONSULTORIOS (ID_CONSULTORIO) values ('4');
Insert into CURSODB.TBL_CONSULTORIOS (ID_CONSULTORIO) values ('5');
Insert into CURSODB.TBL_CONSULTORIOS (ID_CONSULTORIO) values ('6');
Insert into CURSODB.TBL_CONSULTORIOS (ID_CONSULTORIO) values ('7');
Insert into CURSODB.TBL_CONSULTORIOS (ID_CONSULTORIO) values ('8');
Insert into CURSODB.TBL_CONSULTORIOS (ID_CONSULTORIO) values ('9');
Insert into CURSODB.TBL_CONSULTORIOS (ID_CONSULTORIO) values ('10');
Insert into CURSODB.TBL_CONSULTORIOS (ID_CONSULTORIO) values ('11');
