--------------------------------------------------------
--  Ref Constraints for Table TBL_CITAS
--------------------------------------------------------

  ALTER TABLE "CURSODB"."TBL_CITAS" ADD CONSTRAINT "FK_ID_PACIENTE" FOREIGN KEY ("ID_PACIENTE")
	  REFERENCES "CURSODB"."TBL_PACIENTES" ("ID_PACIENTE") ENABLE;
  ALTER TABLE "CURSODB"."TBL_CITAS" ADD CONSTRAINT "FK_ID_CONSULTORIO" FOREIGN KEY ("ID_CONSULTORIO")
	  REFERENCES "CURSODB"."TBL_CONSULTORIOS" ("ID_CONSULTORIO") ENABLE;
  ALTER TABLE "CURSODB"."TBL_CITAS" ADD CONSTRAINT "FK_NRP_ODONTOLOGO" FOREIGN KEY ("NRP_ODONTOLOGO")
	  REFERENCES "CURSODB"."TBL_ODONTOLOGOS" ("NRP_ODONTOLOGO") ENABLE;
  ALTER TABLE "CURSODB"."TBL_CITAS" ADD CONSTRAINT "FK_ID_ESTADO" FOREIGN KEY ("ID_ESTADO")
	  REFERENCES "CURSODB"."TBL_ESTADOS" ("ID_ESTADOS") ENABLE;
