--------------------------------------------------------
--  Constraints for Table TBL_ODONTOLOGOS
--------------------------------------------------------

  ALTER TABLE "CURSODB"."TBL_ODONTOLOGOS" MODIFY ("NRP_ODONTOLOGO" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_ODONTOLOGOS" MODIFY ("ID_ESPECIALIDAD" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_ODONTOLOGOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_ODONTOLOGOS" MODIFY ("CORREO" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_ODONTOLOGOS" ADD CONSTRAINT "PK_NRP_ODONTOLOGO" PRIMARY KEY ("NRP_ODONTOLOGO")
  USING INDEX "CURSODB"."IDX_PK_NRP_ODONTOLOGO"  ENABLE;
