--------------------------------------------------------
--  Constraints for Table TBL_ESPECIALIDADES
--------------------------------------------------------

  ALTER TABLE "CURSODB"."TBL_ESPECIALIDADES" MODIFY ("ID_ESPECIALIDAD" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_ESPECIALIDADES" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_ESPECIALIDADES" ADD CONSTRAINT "PK_ID_ESPECIALIDAD" PRIMARY KEY ("ID_ESPECIALIDAD")
  USING INDEX "CURSODB"."IDX_PK_ID_ESPECIALIDAD"  ENABLE;
