--------------------------------------------------------
--  Constraints for Table TBL_TRATAMIENTOS
--------------------------------------------------------

  ALTER TABLE "CURSODB"."TBL_TRATAMIENTOS" MODIFY ("ID_TRATAMIENTO" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_TRATAMIENTOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_TRATAMIENTOS" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_TRATAMIENTOS" MODIFY ("COSTO_BASE" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_TRATAMIENTOS" ADD CONSTRAINT "PK_ID_TRATAMIENTO" PRIMARY KEY ("ID_TRATAMIENTO")
  USING INDEX "CURSODB"."IDX_PK_ID_TRATAMIENTO"  ENABLE;
