--------------------------------------------------------
--  Constraints for Table TBL_PACIENTES
--------------------------------------------------------

  ALTER TABLE "CURSODB"."TBL_PACIENTES" MODIFY ("ID_PACIENTE" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_PACIENTES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_PACIENTES" MODIFY ("DNI" NOT NULL ENABLE);
  ALTER TABLE "CURSODB"."TBL_PACIENTES" ADD CONSTRAINT "PK_ID_PACIENTES" PRIMARY KEY ("ID_PACIENTE")
  USING INDEX "CURSODB"."IDX_PK_ID_PACIENTES"  ENABLE;
